global:
  ## Hyperkube image to use when getting/deleting ThirdPartyResources
  ##
  hyperkube:
    repository: quay.io/coreos/hyperkube
    tag: v1.5.2_coreos.1
    pullPolicy: IfNotPresent

## Prometheus-operator image
##
image:
  repository: quay.io/coreos/prometheus-operator
  tag: v0.4.0
  pullPolicy: IfNotPresent

## If true, collect & send anonymous usage statistics
## Ref: https://github.com/coreos/prometheus-operator#installation
##
sendAnalytics: true

## Prometheus-operator resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 50Mi
