{{- if .Values.prometheus.cleanup }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-delete
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-delete-prometheus
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
      name: {{ template "fullname" . }}-delete-prometheus
    spec:
      containers:
        - name: delete-service
          image: "{{ .Values.global.hyperkube.repository }}:{{ .Values.global.hyperkube.tag }}"
          imagePullPolicy: "{{ .Values.global.hyperkube.pullPolicy }}"
          command: ["./kubectl","-n","{{ .Release.Namespace }}","delete","svc/prometheus"]
        - name: delete-statefulset
          image: "{{ .Values.global.hyperkube.repository }}:{{ .Values.global.hyperkube.tag }}"
          imagePullPolicy: "{{ .Values.global.hyperkube.pullPolicy }}"
          command: ["./kubectl","-n","{{ .Release.Namespace }}","delete","statefulsets/prometheus-{{ .Values.prometheus.name }}"]
      restartPolicy: Never
{{- end }}
