apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: grafana
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-grafana
data:
  prometheus-datasource.json: |
    {
        "access": "proxy",
        "basicAuth": false,
        "name": "prometheus",
        "type": "prometheus",
        "url": "http://prometheus-{{ .Values.prometheus.name }}.{{ .Release.Namespace }}.svc:9090"
    }
{{ (.Files.Glob "grafana/*.json").AsConfig | indent 2 }}
