apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus
    heritage: {{ .Release.Service }}
    prometheus: "{{ .Values.prometheus.name }}"
    release: {{ .Release.Name }}
  name: prometheus-{{ .Values.prometheus.name }}-rules
data:
{{ (.Files.Glob "rules/*.rules").AsConfig | indent 2 }}
