apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus
    heritage: {{ .Release.Service }}
    prometheus: "{{ .Values.prometheus.name }}"
    release: {{ .Release.Name }}
  name: prometheus-{{ .Values.prometheus.name }}
data:
  prometheus.yaml: |
    alerting:
      alertmanagers:
        - kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - action: keep
              regex: alertmanager-{{ .Values.alertmanager.name }}
              source_labels:
                - __meta_kubernetes_service_name
            - action: keep
              regex: {{ .Release.Namespace }}
              source_labels:
                - __meta_kubernetes_namespace
            - action: keep
              regex: http
              source_labels:
                - __meta_kubernetes_endpoint_port_name
          scheme: http

    global:
      evaluation_interval: 15s
      scrape_interval: 15s

    rule_files:
      - /etc/prometheus/rules/*.rules

    scrape_configs:
      - job_name: kubelets
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          # Skip verification until we have resolved why the certificate validation
          # for the kubelet on API server nodes fail.
          insecure_skip_verify: true

      # Scrapes the endpoint lists for the kube-dns server. Which we consider
      # part of a default setup.
      - job_name: kube-components
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: replace
            source_labels: [__meta_kubernetes_service_label_k8s_app]
            target_label: job
          - action: keep
            regex: ".*-prometheus-discovery"
            source_labels: [__meta_kubernetes_service_name]
          - action: keep
            regex: "http-metrics.*|https-metrics.*"
            source_labels: [__meta_kubernetes_endpoint_port_name]
          - action: replace
            regex: "https-metrics.*"
            replacement: https
            source_labels: [__meta_kubernetes_endpoint_port_name]
            target_label: __scheme__
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

      # Scrapes the endpoint lists for the Kubernetes API server, kube-state-metrics,
      # and node-exporter, which we all consider part of a default setup.
      - job_name: standard-endpoints
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: keep
            regex: prometheus-{{ .Values.prometheus.name }}|{{ template "fullname" . }}-node-exporter|{{ template "fullname" . }}-kube-state-metrics
            source_labels: [__meta_kubernetes_service_name]
          - action: replace
            source_labels: [__meta_kubernetes_service_name]
            target_label: job
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          # As for kubelets, certificate validation fails for the API server (node)
          # and we circumvent it for now.
          insecure_skip_verify: true
