{{- if not .Values.prometheus.config.specifiedInValues }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "prometheus"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
  name: prometheus-{{ .Release.Name }}
data:
  prometheus.yaml: {{ include (print  (dir $.Template.Name) "/_prometheus.yaml.tpl") . | b64enc | quote }}
  configmaps.json: {{ include (print  (dir $.Template.Name) "/_configmaps.json.tpl") . | b64enc | quote }}
{{- end }}
